baseurl             = "https://sluga.netlify.com"
theme               = "cocoa-eh-hugo-theme"
builddrafts         = true
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Website author"
title               = "Website title"
disqusshortname     = ""
pluralizelisttitles = false

[permalinks]
blog                = "blog/:slug/"

[params]
dateform            = "2 Jan, 2006"
dateformfull        = "Mon Jan 2 2006 15:04:05 MST"
description         = "Example blog"
copyright           = "Copyright © 2018 Website author"
# copyrightUrl      = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile            = "img/logo.png"
faviconfile         = "img/logo.png"
highlightjs         = true
progressively       = false # for images, by default = true
share               = false # does not seem to be working on netlify
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount     = 5
github              = "example"
#email              = "you@example.com"
#linkedin           = "john-example-aa80ue8è"
twitter             = "example"
#facebook           = "facebook_id"
#instagram          = "instagram_id"
#itch_io            = "itch_io_id"
social_banner       = "img/banner.png"
usesmallsummarycard = true
posts_navigation    = true
# issoHost          = "comments.domain.tld:1234"
# githubRepo        = "githubUsername/repositoryName/tree/master"
small_banner_logo   = false

## added, not here by default
uselatex    = true        # added; missing by default
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
##

[params.colors]
identifier          = "#527fc1f"  # links, inline ("#527fc1f")
identifier_dark     = "#1a3152"   # hovering over links ("#1a3152")
trivial             = "#6a7a8b"   # several things ("#6a7a8b")
foreground          = "#181d2a"   # ("#181d2a")
background          = "#F0F0F0"   # inline code background ("#f9f9f9")
background_dark     = "#F0F0F0"   # block code background ("#282a36")
code                = "#1a3152"   # ("#87a5d2")
type                = "#97d28b"   # ? ("#97d28b") 
special             = "#ffcb8d"   # ? ("#ffcb8d") 
value               = "#96c2d7"   # strings, numbers in code ("#96c2d7") 
statement           = "#ff8e91"   # ? ("#ff8e91") 
